ATTACHMENTS_USE_S3 = False
FLASK_DEBUG = True
DEBUG = True
SENTRY_DSN = None
SQLALCHEMY_ECHO = True
SSL_REQUIRED = False

# Flask-DebugToolbar settings
DEBUG_TB_INTERCEPT_REDIRECTS = False
DEBUG_TB_PROFILER_ENABLED = True
