"""empty message

Revision ID: 02d450e7809f
Revises: 73f2ae3e61b6
Create Date: 2018-02-28 16:45:13.474198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d450e7809f'
down_revision = '73f2ae3e61b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
