"""empty message

Revision ID: 12dfdeb4c021
Revises: 13a87f5db5f8
Create Date: 2018-04-01 09:29:22.170403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12dfdeb4c021'
down_revision = '13a87f5db5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'extra_data')
    # ### end Alembic commands ###
