"""empty message

Revision ID: 13a87f5db5f8
Revises: 821aacfa0e36
Create Date: 2018-03-30 19:24:30.241397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a87f5db5f8'
down_revision = '821aacfa0e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_data_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('visible_in_lists', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_set_id'], ['location_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('location', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('location', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'lon')
    op.drop_column('location', 'lat')
    op.drop_table('location_data_field')
    # ### end Alembic commands ###
