"""add is_hidden field

Revision ID: 14d0310ab80f
Revises: c4166678fb79
Create Date: 2022-04-19 17:23:29.131789

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "14d0310ab80f"
down_revision = "c4166678fb79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("is_hidden", sa.Boolean(), nullable=True))
    op.add_column("form", sa.Column("is_hidden", sa.Boolean(), nullable=True))
    op.add_column(
        "location_set", sa.Column("is_hidden", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "participant_set", sa.Column("is_hidden", sa.Boolean(), nullable=True)
    )

    query_event = sa.sql.text("UPDATE event SET is_hidden = 'f';")
    query_form = sa.sql.text("UPDATE form SET is_hidden = 'f';")
    query_location_set = sa.sql.text(
        "UPDATE location_set SET is_hidden = 'f';"
    )
    query_participant_set = sa.sql.text(
        "UPDATE participant_set SET is_hidden = 'f';"
    )

    connection = op.get_bind()

    connection.execute(query_event)
    connection.execute(query_form)
    connection.execute(query_location_set)
    connection.execute(query_participant_set)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant_set", "is_hidden")
    op.drop_column("location_set", "is_hidden")
    op.drop_column("form", "is_hidden")
    op.drop_column("event", "is_hidden")
    # ### end Alembic commands ###
