"""empty message

Revision ID: 14d29a283f2b
Revises: b414cf29d789
Create Date: 2018-03-17 16:35:50.218734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14d29a283f2b'
down_revision = 'b414cf29d789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_set', 'admin_divisions_graph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_set', sa.Column('admin_divisions_graph', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
