"""add has_coordinates flag

Revision ID: 151d1097b801
Revises: 3f4fcfd3d063
Create Date: 2020-01-22 15:43:32.877621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151d1097b801'
down_revision = '3f4fcfd3d063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'location_type', sa.Column(
            'has_coordinates', sa.Boolean(), server_default=sa.text('false'),
            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_type', 'has_coordinates')
    # ### end Alembic commands ###
