"""Add deployment locales and populate locale table

Revision ID: 174754b75952
Revises: 98cab6d3d1d3
Create Date: 2019-01-12 13:07:34.523462

"""
from alembic import op
import sqlalchemy as sa

from apollo.settings import LANGUAGES


# revision identifiers, used by Alembic.
revision = '174754b75952'
down_revision = '98cab6d3d1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    locale_table = op.create_table('locale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_locales',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('locale_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locale_id'], ['locale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id', 'locale_id')
    )

    op.bulk_insert(
        locale_table,
        [{'code': k, 'name': v} for k, v in LANGUAGES.items()]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_locales')
    op.drop_table('locale')
    # ### end Alembic commands ###
