"""empty message

Revision ID: 1f1cbf7ff3cb
Revises: 12dfdeb4c021
Create Date: 2018-04-03 09:52:03.691710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1cbf7ff3cb'
down_revision = '12dfdeb4c021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_data_field')
    op.drop_table('location_data_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_data_field',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visible_in_lists', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_set_id'], ['location_set.id'], name='location_data_field_location_set_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='location_data_field_pkey')
    )
    op.create_table('participant_data_field',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('participant_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('visible_in_lists', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_set_id'], ['participant_set.id'], name='participant_data_field_participant_set_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participant_data_field_pkey')
    )
    # ### end Alembic commands ###
