"""empty message

Revision ID: 24cb5e1bc3a1
Revises: 72bf54a6cfc5
Create Date: 2018-03-05 20:44:21.304602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cb5e1bc3a1'
down_revision = '72bf54a6cfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('incident_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'incident_description')
    # ### end Alembic commands ###
