"""empty message

Revision ID: 277d549bf870
Revises: 3b9c2321ae29
Create Date: 2018-05-22 02:09:53.825449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '277d549bf870'
down_revision = '3b9c2321ae29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('submission_data_idx', 'submission', ['data'], unique=False, postgresql_using='gin')
    op.drop_column('submission', 'quality_assurance_status')
    op.drop_column('submission', 'confidence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('submission', sa.Column('quality_assurance_status', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('submission_data_idx', table_name='submission')
    # ### end Alembic commands ###
