"""empty message

Revision ID: 30efc050b273
Revises: 872591ee58b4
Create Date: 2018-12-21 13:49:16.445006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30efc050b273'
down_revision = '872591ee58b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_type_path_location_set_id_fkey', 'location_type_path', type_='foreignkey')
    op.create_foreign_key(None, 'location_type_path', 'location_set', ['location_set_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location_type_path', type_='foreignkey')
    op.create_foreign_key('location_type_path_location_set_id_fkey', 'location_type_path', 'location_set', ['location_set_id'], ['id'])
    # ### end Alembic commands ###
