"""add is_finalized for tracking finalized divisions for the location set

Revision ID: 32263b7ab47e
Revises: e1af791c1a40
Create Date: 2020-05-13 15:21:39.031445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32263b7ab47e'
down_revision = 'e1af791c1a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_set', sa.Column('is_finalized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location_set', 'is_finalized')
    # ### end Alembic commands ###
