"""Change I18N implementation

Revision ID: 336dd1cfd7d1
Revises: 60499944ad25
Create Date: 2019-01-25 12:44:28.477848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '336dd1cfd7d1'
down_revision = '60499944ad25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_type_translation')
    op.drop_table('participant_translation')
    op.drop_table('location_translation')
    op.add_column('location', sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('location_type', sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('participant', sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'name_translations')
    op.drop_column('location_type', 'name_translations')
    op.drop_column('location', 'name_translations')
    op.create_table('location_translation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['location.id'], name='location_translation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale', name='location_translation_pkey')
    )
    op.create_table('participant_translation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['participant.id'], name='participant_translation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale', name='participant_translation_pkey')
    )
    op.create_table('location_type_translation',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['location_type.id'], name='location_type_translation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'locale', name='location_type_translation_pkey')
    )
    # ### end Alembic commands ###
