"""empty message

Revision ID: 37fa6062fb7c
Revises: 1f1cbf7ff3cb
Create Date: 2018-04-03 11:09:07.369817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fa6062fb7c'
down_revision = '1f1cbf7ff3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_data_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('visible_in_lists', sa.Boolean(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_set_id'], ['location_set.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_data_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('visible_in_lists', sa.Boolean(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_set_id'], ['participant_set.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_data_field')
    op.drop_table('location_data_field')
    # ### end Alembic commands ###
