"""empty message

Revision ID: 3983b54a6b7d
Revises: 37fa6062fb7c
Create Date: 2018-04-04 09:01:38.265636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3983b54a6b7d'
down_revision = '37fa6062fb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'other_code')
    op.drop_column('location', 'political_code')
    op.drop_column('location_type', 'has_other_code')
    op.drop_column('location_type', 'has_political_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_type', sa.Column('has_political_code', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('location_type', sa.Column('has_other_code', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('political_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('other_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
