"""empty message

Revision ID: 49879d5c432a
Revises: d755511087a6
Create Date: 2018-04-08 11:57:00.890428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49879d5c432a'
down_revision = 'd755511087a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_deployment_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'deployment_id')
    op.add_column('resource', sa.Column('deployment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resource', 'deployment', ['deployment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'deployment_id')
    op.add_column('event', sa.Column('deployment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_deployment_id_fkey', 'event', 'deployment', ['deployment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
