"""empty message

Revision ID: 564b430073ed
Revises: 7ae8ac17bb1a
Create Date: 2018-02-11 19:09:18.586362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564b430073ed'
down_revision = '7ae8ac17bb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_name_key', 'role', type_='unique')
    op.create_unique_constraint(None, 'role', ['deployment_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.create_unique_constraint('role_name_key', 'role', ['name'])
    # ### end Alembic commands ###
