"""empty message

Revision ID: 5de117ddc0b3
Revises: 7a7a7b680b77
Create Date: 2018-03-29 17:53:07.634150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de117ddc0b3'
down_revision = '7a7a7b680b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('participant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'participant', ['participant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'participant_id')
    # ### end Alembic commands ###
