"""add field visibility columns for participants

Revision ID: 62783e6332b6
Revises: 17e9d721d8cc
Create Date: 2019-08-23 19:00:33.196848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62783e6332b6'
down_revision = '17e9d721d8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_set', sa.Column('gender_hidden', sa.Boolean(), nullable=True))
    op.add_column('participant_set', sa.Column('partner_hidden', sa.Boolean(), nullable=True))
    op.add_column('participant_set', sa.Column('role_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant_set', 'role_hidden')
    op.drop_column('participant_set', 'partner_hidden')
    op.drop_column('participant_set', 'gender_hidden')
    # ### end Alembic commands ###
