"""empty message

Revision ID: 72bf54a6cfc5
Revises: e105790ce305
Create Date: 2018-03-05 16:07:03.585339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72bf54a6cfc5'
down_revision = 'e105790ce305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('overridden_fields', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('submission', 'overidden_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('overidden_fields', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('submission', 'overridden_fields')
    # ### end Alembic commands ###
