"""empty message

Revision ID: 7868e9ee5263
Revises: a772db4eee68
Create Date: 2018-03-05 07:18:08.117748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7868e9ee5263'
down_revision = 'a772db4eee68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('overidden_fields', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'overidden_fields')
    # ### end Alembic commands ###
