"""add participant locale

Revision ID: 7cbcd7443117
Revises: c49246964b9d
Create Date: 2022-07-21 06:15:32.406241

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7cbcd7443117"
down_revision = "c49246964b9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participant", sa.Column("locale", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant", "locale")
    # ### end Alembic commands ###
