"""empty message

Revision ID: 821aacfa0e36
Revises: 5de117ddc0b3
Create Date: 2018-03-30 07:08:19.769437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '821aacfa0e36'
down_revision = '5de117ddc0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission', sa.Column('quality_assurance_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'quality_assurance_status')
    op.drop_column('submission', 'confidence')
    # ### end Alembic commands ###
