"""empty message

Revision ID: 88c83b181af3
Revises: ff01b1cb464b
Create Date: 2018-03-10 21:51:53.782481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88c83b181af3'
down_revision = 'ff01b1cb464b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_data_field',
    sa.Column('participant_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('visible_in_lists', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['participant_set_id'], ['participant_set.id'], ),
    sa.PrimaryKeyConstraint('participant_set_id')
    )
    op.drop_column('participant_set', 'extra_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_set', sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('participant_data_field')
    # ### end Alembic commands ###
