"""empty message

Revision ID: 8bb7c36e3089
Revises: f9f8512ac458
Create Date: 2018-02-22 14:49:44.239030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb7c36e3089'
down_revision = 'f9f8512ac458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant_group', sa.Column('participant_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant_group', 'participant_set', ['participant_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant_group', type_='foreignkey')
    op.drop_column('participant_group', 'participant_set_id')
    # ### end Alembic commands ###
