"""Add checklist conflict tracking field

Revision ID: 98cab6d3d1d3
Revises: e072b671cf70
Create Date: 2019-01-06 09:28:33.246918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cab6d3d1d3'
down_revision = '2d9011b4a9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('track_data_conflicts', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'track_data_conflicts')
    # ### end Alembic commands ###
