"""Add location coordinates and logical check verification

Revision ID: 9fe7f8aa7849
Revises: e0556a0d4ec8
Create Date: 2019-05-23 19:44:29.822526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fe7f8aa7849'
down_revision = 'e0556a0d4ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('geopoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission', sa.Column('verified_logical_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'verified_logical_checks')
    op.drop_column('submission', 'geopoint')
    # ### end Alembic commands ###
