"""empty message

Revision ID: a0b279dd6ade
Revises: fb7fafec60f9
Create Date: 2018-02-24 13:02:05.177261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b279dd6ade'
down_revision = 'fb7fafec60f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'phone', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone', type_='unique')
    # ### end Alembic commands ###
