"""empty message

Revision ID: a772db4eee68
Revises: b887f56f2202
Create Date: 2018-03-03 05:40:29.766276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

from apollo.submissions.models import Submission

# revision identifiers, used by Alembic.
revision = 'a772db4eee68'
down_revision = 'b887f56f2202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('submission', sa.Column('incident_status', sqlalchemy_utils.types.choice.ChoiceType(Submission.INCIDENT_STATUSES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'incident_status')
    op.drop_column('submission', 'extra_data')
    # ### end Alembic commands ###
