"""add not_opened field

Revision ID: b3ccd538959e
Revises: e00e521a0434
Create Date: 2021-08-03 09:41:18.244493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3ccd538959e'
down_revision = 'e00e521a0434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'submission',
        sa.Column('not_opened', sa.Boolean(), nullable=False,
                  server_default='False'))
    op.alter_column('submission', 'not_opened', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'not_opened')
    # ### end Alembic commands ###
