"""empty message

Revision ID: b414cf29d789
Revises: 24d7fb4ea967
Create Date: 2018-03-14 17:27:34.729384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414cf29d789'
down_revision = '24d7fb4ea967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('accredited_voters_tag', sa.String(), nullable=True))
    op.add_column('form', sa.Column('registered_voters_tag', sa.String(), nullable=True))
    op.drop_column('form', 'registered_votes_tag')
    op.drop_column('form', 'accreditated_voters_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('accreditated_voters_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('form', sa.Column('registered_votes_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('form', 'registered_voters_tag')
    op.drop_column('form', 'accredited_voters_tag')
    # ### end Alembic commands ###
