"""empty message

Revision ID: b887f56f2202
Revises: 02d450e7809f
Create Date: 2018-03-02 15:25:39.955334

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from apollo.submissions.models import Submission


# revision identifiers, used by Alembic.
revision = 'b887f56f2202'
down_revision = '02d450e7809f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('quarantine_status', sqlalchemy_utils.types.choice.ChoiceType(Submission.QUARANTINE_STATUSES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'quarantine_status')
    # ### end Alembic commands ###
