"""Add geopoint field to submissions

Revision ID: bc84eb2bd8f1
Revises: 336dd1cfd7d1
Create Date: 2019-03-05 21:24:44.213889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc84eb2bd8f1'
down_revision = '336dd1cfd7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('geopoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'geopoint')
    # ### end Alembic commands ###
