"""added `turnout_registered_voters_tag` field to the forms table

Revision ID: c49246964b9d
Revises: 69c602dc37b2
Create Date: 2023-01-27 22:52:10.432621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49246964b9d'
down_revision = '69c602dc37b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('turnout_registered_voters_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'turnout_registered_voters_tag')
    # ### end Alembic commands ###
