"""empty message

Revision ID: cee9b42e2c0a
Revises: 860f7d0f3665
Create Date: 2018-02-22 11:21:29.504174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee9b42e2c0a'
down_revision = '860f7d0f3665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_groups_participants',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['participant_group.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_groups_participants')
    # ### end Alembic commands ###
