"""empty message

Revision ID: d516a4375337
Revises: 1b9f69ec2019
Create Date: 2018-03-20 11:44:06.255916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd516a4375337'
down_revision = '1b9f69ec2019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission')
    op.drop_table('user_permission')
    op.drop_table('role_resource_permission')
    op.drop_table('user_resource_permission')
    op.drop_table('base_permission')

    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_resource_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'resource_id')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_resource_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id')
    )
    op.create_table('users_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_permission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('base_permission_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], name='base_permission_deployment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='base_permission_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_resource_permission',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_permission_id'], ['base_permission.id'], name='user_resource_permission_base_permission_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], name='user_resource_permission_resource_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_resource_permission_user_id_fkey', ondelete='CASCADE')
    )
    op.create_table('role_resource_permission',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_permission_id'], ['base_permission.id'], name='role_resource_permission_base_permission_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], name='role_resource_permission_resource_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_resource_permission_role_id_fkey', ondelete='CASCADE')
    )
    op.create_table('user_permission',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_permission_id'], ['base_permission.id'], name='user_permission_base_permission_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_permission_user_id_fkey', ondelete='CASCADE')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['base_permission_id'], ['base_permission.id'], name='role_permission_base_permission_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_permission_role_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('users_permissions')
    op.drop_table('user_resource_permissions')
    op.drop_table('roles_permissions')
    op.drop_table('role_resource_permissions')
    op.drop_table('permission')
    # ### end Alembic commands ###
