"""empty message

Revision ID: d755511087a6
Revises: 3983b54a6b7d
Create Date: 2018-04-08 06:01:04.970023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd755511087a6'
down_revision = '3983b54a6b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'conflicts')
    # ### end Alembic commands ###
