"""change logo to brand image

Revision ID: e00e521a0434
Revises: d1b58fcfbd26
Create Date: 2021-04-01 10:24:10.133902

"""
import depot
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e00e521a0434'
down_revision = 'd1b58fcfbd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'deployment',
        sa.Column(
            'brand_image', depot.fields.sqlalchemy.UploadedFileField(),
            nullable=True))
    op.drop_column('deployment', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'deployment',
        sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('deployment', 'brand_image')
    # ### end Alembic commands ###
