"""added the unreachable attribute to submissions

Revision ID: e0556a0d4ec8
Revises: 28d28943b1eb
Create Date: 2019-04-22 01:35:48.826766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0556a0d4ec8'
down_revision = '28d28943b1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column(
        'unreachable', sa.Boolean(), nullable=False, server_default='False'))
    op.alter_column('submission', 'unreachable', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'unreachable')
    # ### end Alembic commands ###
