"""empty message

Revision ID: e072b671cf70
Revises: 30efc050b273
Create Date: 2018-12-21 13:53:25.519762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e072b671cf70'
down_revision = '30efc050b273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###
