"""empty message

Revision ID: e105790ce305
Revises: 7868e9ee5263
Create Date: 2018-03-05 13:03:22.299298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e105790ce305'
down_revision = '7868e9ee5263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_version', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_version', 'data')
    # ### end Alembic commands ###
