"""empty message

Revision ID: e1b3a666390f
Revises: a0b279dd6ade
Create Date: 2018-02-25 03:37:45.499915

"""
from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b3a666390f'
down_revision = 'a0b279dd6ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'geometry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
