"""empty message

Revision ID: f2410395f557
Revises: e072b671cf70
Create Date: 2018-12-29 12:38:48.760387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2410395f557'
down_revision = 'e072b671cf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('track_data_conflicts', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'track_data_conflicts')
    # ### end Alembic commands ###
