"""empty message

Revision ID: ff01b1cb464b
Revises: 24cb5e1bc3a1
Create Date: 2018-03-08 09:40:41.748225

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from apollo.submissions.models import Submission


# revision identifiers, used by Alembic.
revision = 'ff01b1cb464b'
down_revision = '24cb5e1bc3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('verification_status', sqlalchemy_utils.types.choice.ChoiceType(Submission.VERIFICATION_STATUSES), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'verification_status')
    # ### end Alembic commands ###
